version: 2
jobs:
  test_in_vm:
    working_directory: ~/mcrain

    ## see https://circleci.com/docs/2.0/executor-types/#machine-executor-overview
    machine: true

    steps:
      - checkout

      - run:
          name: Check docker version
          command: |
            set -x
            docker version
            docker info

      - run:
          name: Check ruby version
          command: |
            set -x
            rvm version
            rvm list
            ruby -v
            gem --version
            gem env
            bundle --version

      - run:
          name: Open docker TCP port
          command: |
            set -x
            echo 'DOCKER_OPTS="$DOCKER_OPTS -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"' | sudo tee -a /etc/default/docker
            sudo service docker restart

      - run: docker pull mysql:5.5
      - run: docker pull redis:2.8.19
      - run: docker pull rabbitmq:3.4.4-management
      - run: docker pull hectcastro/riak:latest

      - run: bundle install --jobs=4 --path=vendor/bundle

      - run:
          name: test
          command: bundle exec rake spec
          environment:
            DOCKER_HOST: tcp://127.0.0.1:2375


  test_in_container:
    working_directory: ~/mcrain

    docker:
      - image: circleci/ruby:2.3.5

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Check docker version
          command: |
            set -x
            docker version
            docker info

      - run: docker build -t rspec-runner -f .circleci/rspec-runner/Dockerfile .

      - run: docker pull mysql:5.5
      - run: docker pull redis:2.8.19
      - run: docker pull rabbitmq:3.4.4-management
      - run: docker pull hectcastro/riak:latest

      - run:
          name: Setup rspec-runner environment variables
          command: |
            printenv | sort | grep -Ev '^(DOCKER_*|CIRCLE_BUILD_TOKEN)=' | grep -E '^(CI=|CIRCLECI=|CIRCLE_)' > .circleci/env
            echo "DOCKER_HOST=tcp://127.0.0.1:2375" >> .circleci/env

      - run:
          name: Run socat to connect remote docker socket
          command: docker run -d --restart=always --name socat -v /run/docker.sock:/run/docker.sock alpine/socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CLIENT:/run/docker.sock

      - run:
          name: Run rake spec in remote docker
          command: docker run --rm --env-file .circleci/env --net=container:socat rspec-runner bundle exec rake spec


workflows:
  version: 2
  tests:
    jobs:
      - test_in_vm
      - test_in_container
